//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_21_Kiko
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lab_21Entities : DbContext
    {
        public Lab_21Entities()
            : base("name=Lab_21Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static Lab_21Entities context;
        public static Lab_21Entities GetContext()
        {
            if (context == null) context = new Lab_21Entities();
            return context;
        }
        public virtual DbSet<Parts_reference_> Parts_reference_ { get; set; }
        public virtual DbSet<Product_composition> Product_composition { get; set; }
        public virtual DbSet<Product_Reference> Product_Reference { get; set; }
        public virtual DbSet<Release_plan> Release_plan { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Workshops> Workshops { get; set; }
    }
}
